# docker-compose.yml
services:
  web01:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: web01
    ports:
      - "2221:22"

  web02:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: web02
    ports:
      - "2222:22"

  db01:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: db01
    ports:
      - "2223:22"